# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='begin_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='trip',
            name='other_users',
            field=models.ManyToManyField(related_name='other_users_trip', to='login_reg.User'),
        ),
    ]
