# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20170626_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
